name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK and Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        java-version: '17'
    - name: Decode Keystore
      env:
        SIGNING_KEYSTORE_BASE64: ${{ secrets.SIGNING_KEYSTORE_BASE64 }}
      run: |
        echo "$SIGNING_KEYSTORE_BASE64" | base64 --decode > app/key.jks
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleRelease
    - name: Upload Release APKs
      uses: actions/upload-artifact@v4
      with:
        name: release-apks
        path: app/build/outputs/apk/release/*.apk