name: Release APKs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: false

      - name: Prepare keystore and gradle.properties
        shell: bash
        run: |
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "Decoding keystore from secrets"
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > key.jks
          fi
          {
            echo "SIGNING_STORE_FILE=key.jks"
            echo "SIGNING_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}"
            echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}"
            echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}"
          } >> gradle.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release split APKs
        run: ./gradlew :app:assembleRelease --stacktrace --no-daemon

      - name: Collect APKs
        run: |
          mkdir -p artifacts
          echo "Listing release APK outputs:"
          ls -R app/build/outputs/apk/release || true
          armv7a=$(find app/build/outputs/apk/release -name "*armeabi-v7a*.apk" | head -n1)
          arm64=$(find app/build/outputs/apk/release -name "*arm64-v8a*.apk" | head -n1)
          if [ -n "$armv7a" ]; then cp "$armv7a" artifacts/app-armeabi-v7a.apk; else echo "armeabi-v7a apk not found"; fi
          if [ -n "$arm64" ]; then cp "$arm64" artifacts/app-arm64-v8a.apk; else echo "arm64-v8a apk not found"; fi

      - name: Upload artifacts (for debugging if release fails)
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: artifacts/*.apk
          if-no-files-found: warn

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/app-armeabi-v7a.apk
            artifacts/app-arm64-v8a.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
