name: Release APKs

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3

      - name: Prepare keystore and gradle.properties
        shell: bash
        run: |
          # 写入签名文件 key.jks（来自仓库 Secrets 的 base64）
          if [ -n "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" ]; then
            echo "Decoding keystore from secrets"
            echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > key.jks
          fi
          # 写入签名配置到 gradle.properties（与 app/build.gradle.kts 读取逻辑匹配）
          {
            echo "SIGNING_STORE_FILE=key.jks"
            echo "SIGNING_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}"
            echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}"
            echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}"
          } >> gradle.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release split APKs
        run: ./gradlew :app:assembleRelease --stacktrace --no-daemon

      - name: Collect APKs
        run: |
          mkdir -p artifacts
          cp app/build/outputs/apk/release/*-armeabi-v7a*.apk artifacts/app-armeabi-v7a.apk || true
          cp app/build/outputs/apk/release/*-arm64-v8a*.apk artifacts/app-arm64-v8a.apk || true

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/app-armeabi-v7a.apk
            artifacts/app-arm64-v8a.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
